apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-api-key-secret-{{ .Release.Name }}"
data:
  {{ .Values.secret.key }}: '{{ required "secret.api.key required!" .Values.secret.api.key | b64enc }}'