apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-api-key-secret-{{ .Release.Name }}"
data:
  {{ .Values.secret.api.keyName }}: '{{ required "secret.api.keyValue required!" .Values.secret.api.keyValue | b64enc }}'
  {{ .Values.secret.domain.keyName }}: '{{ required "secret.api.domain.name required!" .Values.secret.domain.name | b64enc }}'