apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: {{ .Release.Name }}
        spec:
          containers:
          - name: ddns-updater
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            env:
              - name: DDNS_KEY
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Chart.Name }}-api-key-secret-{{ .Release.Name }}"
                    key: {{ .Values.secret.api.keyName }}
            command: ["/bin/sh"]
            args: ["-c", "/bin/echo {{ .Values.secret.domain.name }}; /usr/bin/curl -vvv -s http://sync.afraid.org/u/$(DDNS_KEY)/"]
          restartPolicy: Never

          {{- if .Values.affinity.node.value }}
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: {{ .Values.affinity.weight }}
                  preference:
                    matchExpressions:
                      - key: "{{ .Values.affinity.node.label }}"
                        operator: In
                        values: 
                          {{- range .Values.affinity.node.value }}
                          - {{ . | quote }}
                          {{- end }}
          {{- end }}