apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  labels:
    app: ddns-updater
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ddns-updater
  template:
    metadata:
      labels:
        app: ddns-updater
    spec:
      containers:
      - name: ddns-updater-container
        image: ddns-updater:latest
        imagePullPolicy: Never
        env:
          - name: {{ index .Values "env" "var-api-key" }}
            valueFrom:
              secretKeyRef:
                name: "{{ .Chart.Name }}-api-key-secret-{{ .Release.Name }}"
                key: {{ .Values.secret.api.keyName }}
  restartPolicy: Always

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "network"
              operator: In
              values: ["gbit"]
